version: '3.8'  # Specify the Docker Compose file version

services:
  web:
    image: shubhamade1122/amazon-clone:latest  # Use the official Node.js image
    working_dir: /app  # Set the working directory in the container
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "3000:3000"  # Expose port 3000
    command: ["npm", "start"]  # Command to run when the container starts
