version: '3'
services:
  web:
    build: ./amazon-clone/docker-compose.yaml  # Path where the Dockerfile for "web" service is located
    image: amazon-clone:latest  # Tag the image after building
    ports:
      - "3000:3000"
    depends_on:
      - api
