version: '3.8'  # Specify the version of Docker Compose

services:
  web:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile if it's not named 'Dockerfile'
    image: amazon-clone:latest  # Tag the built image
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
  
