version: '3'
services:
  web:
    image: amazon-clone:latest  # Pull the existing image from the registry
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    image: api-service:latest  # Specify the image for the API service
    ports:
      - "8000:8000"
